### PR TITLE
Fix a bunch of HTML errors

### PR DESCRIPTION
**Pull request by martinthomson**
The `</body>` element seems to contain some un-terminated content, but I can't find that easily.

### CODE REVIEW

**Review by hlflanagan — COMMENTED** [review]
I've updated the doc to remove all irefs (there's no index in this RFC) and fixed most of the other nits you identified. Many thanks! The one thing I didn't change was removing <dl class="reference"> That seems to be required, unless I'm misinterpreting something (which is distinctly possible!)

**Comment by martinthomson** [comment]
Github swallowed your comment. What did you not remove?

**Comment by hlflanagan** [comment]
the dl reference tags

**Comment by martinthomson** [comment]
Ahh. I removed those because none of the dl elements are terminated and it appeared to be inconsistent. Styling is easier with a single list with many elements, which is what this proposes. If you have a reason for many lists, then that is ok too.

**Comment by hlflanagan** [comment]
Ahha! Yes, of course, I see. I'm fixing it and will push it out in a few minutes.

**Pull request closed without merging**
